# Generated by Django 3.1.1 on 2020-09-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0003_auto_20200926_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersgivingtest',
            old_name='question_not_attempted',
            new_name='questions_not_attempted',
        ),
    ]
