# Generated by Django 3.1.1 on 2020-09-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizer', '0004_auto_20200926_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgivingtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
