# Generated by Django 3.1.1 on 2020-10-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0006_auto_20200929_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='camera_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='email_result_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='email_result_testtaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='one_question_per_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_instructions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomizer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='resume_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_score_after_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='strict_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='view_after_test',
            field=models.BooleanField(default=False),
        ),
    ]
