# Generated by Django 3.1.1 on 2020-10-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0007_auto_20201001_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='record_responses',
            field=models.BooleanField(default=False),
        ),
    ]
