# Generated by Django 3.1.1 on 2020-10-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0011_recordedresponses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordedresponses',
            old_name='reponses',
            new_name='responses',
        ),
    ]
