# Generated by Django 3.1.1 on 2020-10-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0014_auto_20201016_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgivingtest',
            name='curr_question',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
