# Generated by Django 3.1.1 on 2020-10-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0015_usersgivingtest_curr_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgivingtest',
            name='curr_question',
        ),
    ]
