# Generated by Django 3.1.1 on 2020-10-23 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizer', '0021_auto_20201023_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedresponses',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
